#!/usr/bin/env python3
# -*- coding: utf-8 -*-

legacy_script_list = [
    "scil_add_tracking_mask_to_pft_maps.py",
    "scil_apply_bias_field_on_dwi.py",
    "scil_apply_transform_to_image.py",
    "scil_apply_transform_to_surface.py",
    "scil_apply_transform_to_tractogram.py",
    "scil_combine_labels.py",
    "scil_compare_connectivity.py",
    "scil_compute_asym_odf_metrics.py",
    "scil_compute_connectivity.py",
    "scil_compute_divide.py",
    "scil_compute_dti_metrics.py",
    "scil_compute_fodf_max_in_ventricles.py",
    "scil_compute_fodf_metrics.py",
    "scil_compute_freewater.py",
    "scil_compute_ihMT_maps.py",
    "scil_compute_kurtosis_metrics.py",
    "scil_compute_lobe_specific_fodf_metrics.py",
    "scil_compute_local_tracking_dev.py",
    "scil_compute_local_tracking.py",
    "scil_compute_maps_for_particle_filter_tracking.py",
    "scil_compute_mean_frf.py",
    "scil_compute_memsmt_fodf.py",
    "scil_compute_memsmt_frf.py",
    "scil_compute_msmt_fodf.py",
    "scil_compute_msmt_frf.py",
    "scil_compute_MT_maps.py",
    "scil_compute_NODDI_priors.py",
    "scil_compute_NODDI.py",
    "scil_compute_pft.py",
    "scil_compute_powder_average.py",
    "scil_compute_qball_metrics.py",
    "scil_compute_rish_from_sh.py",
    "scil_compute_sf_from_sh.py",
    "scil_compute_sh_from_signal.py",
    "scil_compute_ssst_fodf.py",
    "scil_compute_ssst_frf.py",
    "scil_concatenate_dwi.py",
    "scil_convert_sh_basis.py",
    "scil_convert_surface.py",
    "scil_count_non_zero_voxels.py",
    "scil_crop_volume.py",
    "scil_dilate_labels.py",
    "scil_evaluate_connectivity_graph_measures.py",
    "scil_evaluate_connectivity_pairwise_agreement_measures.py",
    "scil_extract_b0.py",
    "scil_extract_dwi_shell.py",
    "scil_filter_connectivity.py",
    "scil_filter_tractogram.py",
    "scil_fit_bingham_to_fodf.py",
    "scil_flip_gradients.py",
    "scil_flip_streamlines.py",
    "scil_flip_surface.py",
    "scil_flip_volume.py",
    "scil_image_math.py",
    "scil_normalize_connectivity.py",
    "scil_print_connectivity_filenames.py",
    "scil_register_tractogram.py",
    "scil_remove_labels.py",
    "scil_remove_outliers_ransac.py",
    "scil_reorder_connectivity.py",
    "scil_resample_bvals.py",
    "scil_resample_tractogram.py",
    "scil_resample_volume.py",
    "scil_reshape_to_reference.py",
    "scil_set_response_function.py",
    "scil_shuffle_streamlines.py",
    "scil_smooth_surface.py",
    "scil_snr_in_roi.py",
    "scil_split_image.py",
    "scil_split_tractogram.py",
    "scil_split_volume_by_ids.py",
    "scil_split_volume_by_labels.py",
    "scil_streamlines_math.py",
    "scil_swap_gradient_axis.py"
]


# test that all scripts can be called
def test_help_option(script_runner):
    for script in legacy_script_list:
        ret = script_runner.run('  ' + script, '--help')
        assert ret.success
